In [ ]:
f = ['banana', 'apple', 'orange']
f1 = sorted(f)
print(f1)

In [41]:
nlist = []
while True:
    inp = input()
    if inp == "done":
        break
    nlist.append(int(inp))

print(sum(nlist), max(nlist), min(nlist))

1
2
3
4
5
done
15 5 1


In [42]:
d = {}
d['kim'] = 1
'kim' in d

True

In [43]:
1 in d

False

In [53]:
d = {}
sentence = input("Enter a sentence: ")
s1 = set(sentence)
for i in s1:
    d[i] = sentence.count(i)
d

Enter a sentence: asidjfiowefjiosjdoafj


{'j': 4, 'd': 2, 'e': 1, 'f': 3, 's': 2, 'w': 1, 'a': 2, 'o': 3, 'i': 3}

In [54]:
d.values()

dict_values([4, 2, 1, 3, 2, 1, 2, 3, 3])

In [55]:
for a, b in d.items():
    print(b)

4
2
1
3
2
1
2
3
3


In [57]:
f = open("new.txt", "w")
for i in range (1,6):
    data = "%d line\n" % i
    f.write(data)
    
f.close()

In [67]:
f1 = open("new.txt", "r")
line = f1.readlines()
print(line)
f1.close()

['1 line\n', '2 line\n', '3 line\n', '4 line\n', '5 line\n']


In [80]:
f2 = open("new.txt", "r")
data = f2.read()
print(data)
f2.close()

1 line
2 line
3 line
4 line
5 line



In [81]:
f2 = open("new.txt", "r")
for line in f2:
    print(line, end="")
f2.close()

1 line
2 line
3 line
4 line
5 line


In [148]:
test = open("test.txt", "w")
order = ["first", "second", "third"]
for i in order:
    data = i + " line\n"
    test.write(data)

test.close()

In [149]:
t = open("test.txt", "r")
a = []
d = {}

for line in t:
    for i in line.split():
        a.append(i)

t.close()

for i in set(a):
    d[i] = a.count(i)

for key, value in d.items():
    print(key, value)


line 3
second 1
first 1
third 1


In [150]:
t = open("test.txt", "r")
a = [i for i in t.read().split()]

for i in set(a):
    d[i] = a.count(i)

for key, value in d.items():
    print(key, value)

line 3
second 1
first 1
third 1


In [151]:
t = open("test.txt", "r")
for i in set([i for i in t.read().split()]):
    d[i] = a.count(i)

for k, v in d.items():
    print(k, v)

line 3
second 1
first 1
third 1


In [171]:
d = {}
t = open("test.txt", "r")
for i in [i for i in t.read().split()]:
    print(i)

first
line
second
line
third
line


In [ ]:
t.read

In [114]:
import os
os.path.exists("test.txt")

True

In [119]:
file = input("Enter a file name: ")
if os.path.exists(file) == True:
    with open(file, "r") as f:
        for line in f:
            print(line.upper(), end="")

Enter a file name: test.txt
FIRST LINE
SECOND LINE
THIRD LINE


In [175]:
def my_len(l):
    
    length = 0
    for i in l:
        length += 1
        
    return length

In [176]:
a = [5, 5, 6, 7, 8, 3]
b = 'I am a boy'
print(len(a), len(b))
print(my_len(a), my_len(b))

6 10
6 10


In [183]:
def say():
    return "hello"

a = say()
print(type(a))

<class 'str'>


In [184]:
def say():
    print("hello")

a = say()
print(type(a))

hello
<class 'NoneType'>


In [186]:
def add(a, b):
    return a + b

def sub(a, b):
    return a - b

def mul(a, b):
    return a * b

def div(a, b):
    return a // b

a = 1
b = 2

c = add(a, b)
d = sub(a, b)
e = mul(a, b)
f = div(a, b)

print(c, d, e, f)

3 -1 2 0


In [209]:
def factorial(n):
    f = 1
    for i in range(1, n+1):
        f = f * i
    return f

factorial(8)

40320

In [222]:
def my_pow(n, a):
    p = 1
    for i in range(a):
        p *= n
    return p

my_pow(2, 4)

16

In [223]:
def add (a, b):
    global add_res
    add_res = a + b
    
add(1,2)
print(add_res)

3


In [230]:
def printName(first, second = 'Lee'):
    print("My name is", first, second + '.')
    
printName("Chloe", "Kim")
printName("Chloe")

My name is Chloe Kim.
My name is Chloe Lee.


In [6]:
def hour_min_sec(second):
    hour = second // 3600
    minut = (second//60 - (hour * 60))
    sec = second % 60
    return (hour, minut, sec)

hour, minut, sec = hour_min_sec(57894)
print("%d시간 %d분 %d초" % (hour, minut, sec))


16시간 4분 54초


In [275]:
l = [3, 5, 9, 1, 2]

def get_min_max(l):
    mi = min(l);  mx = max(l)
    l.remove(mi); l.remove(mx)
    return mi, mx

minV, maxV = get_min_max(l)
print(minV, maxV, l)

1 9 [3, 5, 2]


In [27]:
t = [1,2,3]
def test(a):
    a += [4,5,6]
test(t)
print(t)

[1, 2, 3, 4, 5, 6]


In [28]:
t= {1:'a'}
def test(a):
    a[2] = 'b'
test(t)
print(t)

{1: 'a', 2: 'b'}


위에 친구들... call by value... mutabe....

In [29]:
t = (1,2,3)
def test(a):
    a += (4,5,6)
test(t)
print(t)

(1, 2, 3)


### Dot product(scala)

In [24]:
def dot(v1, v2):
    product = 0
    for key1, value1 in v1.items():
        for key2, value2 in v2.items():
            if key1 == key2:
                product += (value1 * value2)
    print(product)

In [118]:
v1={'a': 5}; v2={'a':3, 'b':2}
dot(v1, v2)

v3={'c':5}; v4={'a':2, 'b':1}
dot(v1, v2)

v5={'a':5, 'b':4}; v6={'a':-1, 'b':2}
dot(v1, v2)

15
15
15


In [96]:
def dotbyinstructor(v1, v2):
    dot_res = 0
    for k in v1:
        if k in v2:
            dot_rest += v1[k] * v2[k]
    return dot_res

In [97]:
def dotbyinstructor1 (v1, v2):
    return sum([v1[k]*v2[k] if k in v2 for k in v1])

print(v1, v2)

SyntaxError: invalid syntax (<ipython-input-97-6dc3603aeb22>, line 2)

In [119]:
def dotbyinstructor3 (v1, v2):
    res = 0
    for k in v1:
        if k in v2:
            res += v1[k] * v2[k]
    return res

In [120]:
print(dotbyinstructor3(v1, v2))

15


### random number

In [30]:
import random

random.choice('abcdefg')

'e'

In [33]:
a = 10
b = 20
random.randint(a,b)

18

In [44]:
random.randrange(a, b+1)

19

In [55]:
random.sample([1,2,3,4,5,6], 3)

[2, 5, 3]

#### 연습문제 7 : 로또 추첨 프로그램
1~45 번호 중 6개의 임의 선택 후 출력

In [68]:
def lottery():
    print("로또를 추첨합니다.")
    print("추첨된 로또 번호 ==>", end=" ")
    for i in range(6):
        print(random.randint(1, 45), end=" ")
    
lottery()

로또를 추첨합니다.
추첨된 로또 번호 ==> 36 35 38 13 37 16 

### Time module

In [67]:
import time

In [62]:
time.time()

1565760549.74058

In [63]:
time.localtime()

time.struct_time(tm_year=2019, tm_mon=8, tm_mday=14, tm_hour=14, tm_min=29, tm_sec=15, tm_wday=2, tm_yday=226, tm_isdst=0)

In [150]:
time.strftime('date: %dth', )

'date: 14th'

#### 연습문제 8. 가장 많이 등장하는 알파벳

In [78]:
def letter_dict(string):
    ld = {}
    for l in string:
        if l in ld:
            ld[l] += 1
        else:
            ld[l] = 1
    return ld

In [165]:
def letter_dict2(string):
    d = {}
    for i in set(string):
        d[i] = string.count(i)
    return d

In [166]:
a = letter_dict2('red apple')
print(a)

{'d': 1, 'e': 2, ' ': 1, 'l': 1, 'r': 1, 'p': 2, 'a': 1}


In [167]:
def max_letter(dictionary):
    maxiCount = 0
    maxiLetter = ""
    for l in dictionary:
        if dictionary[l] > maxiCount:
            maxiCount = dictionary[l]
            maxiLetter = l
    return maxiLetter

In [168]:
def max_letter2(d):
    for k, v in d.items():
        if v == max(d.values()):
            return k

In [263]:
def max_letter3(d):
    return sorted(d.items(), key=lambda x:x[1], reverse=True)[0][0]
print(max_letter3(a))

e


In [269]:
def max_letter4(d):
    k,v = zip(*d.items()) 
    # 들어오는 애들을 묶을 때 붙이는 거고요 함수에다가 넣을 때 달아서 넣으면 풀어서 넘기겠다는 얘기입니다. 
    # *이 두개 붙는 케이스도 있는데, 두개붙는 케이스는 심화된 버전입니다.
    return k[v.index(max(v))]
print(max_letter4(a))

e


In [169]:
print(max_letter2(a))

e


#### 연습문제 9. 두 딕셔너리를 입력하면, 등장한 값을 모두 더한 새로운 딕셔너리 리턴

In [83]:
b = letter_dic('yellow banana')

In [181]:
def comb_dict(a, b):
    uni = set(a).union(set(b))
    c = {}
    for l in uni:
        if l in set(a).intersection(set(b)):
            c[l] = a[l]+b[l]
        elif l not in b:
            c[l] = a[l]
        else:
            c[l] = b[l]
    return c

In [182]:
c=comb_dict(a,b)
print(c)
print(max_letter2(c))

{'e': 3, ' ': 2, 'l': 3, 'r': 1, 'o': 1, 'n': 2, 'y': 1, 'w': 1, 'd': 1, 'b': 1, 'p': 2, 'a': 4}
a


### 과제1 - LCM_GCD.py

In [273]:
import random
#def LCM(I):

   
def main():
    a = []
    for i in range(10):
        a.append(random.randint(1, 100))
    print(a)
    lcm_value=LCM(a)
    gcd_value=GCD(a)
    print('최소공배수:', lcm_value, '최대공약수:', gcd_value)

### 클래스

In [3]:
class Account:
    number = '000-000-000000'
    balance = 0
    rate = 1.0
    
    def deposit(self, money):
        self.balance += money
    def withdraw(self, money):
        sefl.balance -= money
    def obtain_interest(self):
        self.balance += self.balance * (self.rate/100)
        


### 인스턴스

In [4]:
acc1 = Account()
acc2 = Account()
acc3 = Account()

acc1.deposit(500)
acc2.deposit(1000)

print(acc1.balance)
print(acc2.balance)
print(acc3.balance)

500
1000
0


### method

In [5]:
acc1.deposit(500)
acc2.obtain_interest()
print(acc2.balance)

1010.0


###  Constructor

In [6]:
class Account:    
    def __init__ (self, num='000-000-000000', amnt=0, rate=1.0):
        self.number = num
        self.balance = amnt
        self.rate = rate
    def deposit(self, money):
        self.balance += money
    def withdraw(self, money):
        sefl.balance -= money
    def obtain_interest(self):
        self.balance += self.balance * (self.rate/100)

In [7]:
acc1 = Account()
acc2 = Account('110-230-670217', 100, 3.0)

acc1.deposit(500)
acc2.deposit(500)

print(acc1.balance)
print(acc2.balance)

500
600


### Information Hiding

In [8]:
class Account:    
    def __init__ (self, num='000-000-000000', amnt=0, rate=1.0):
        self.number = num
        self.balance = amnt
        self.rate = rate
    def get_balance(self):
        return self.balance
    def set_balance(self, amnt):
        self.balance = amnt
    def deposit(self, money):
        self.balance += money
    def withdraw(self, money):
        sefl.balance -= money
    def obtain_interest(self):
        self.balance += self.balance * (self.rate/100)

In [9]:
acc3 = Account()
print(acc3.get_balance())
acc3.set_balance(300)
print(acc3.get_balance())
print(acc3.balance)

0
300
300


### Static Variable

In [27]:
class Account:
    num_acc = 0 
    def __init__ (self, num='000-000-000000', amnt=0, rate=1.0):
        self.number = num
        self.balance = amnt
        self.rate = rate
        Account.num_acc += 1
    def get_balance(self):
        return self.balance
    def set_balance(self, amnt):
        self.balance = amnt
    def deposit(self, money):
        self.balance += money
    def withdraw(self, money):
        sefl.balance -= money
    def obtain_interest(self):
        self.balance += self.balance * (self.rate/100)
    def __add__(self, another): #두 계좌 통합 기능
        new_acc = Account(amnt=self.balance+another.balance,rate=self.rate)
        return new_acc
    
    def transfer(self, another, amnt):
        self.balance += amnt
        withdraw(another, amnt)

In [23]:
acc1 = Account()
acc2 = Account()
acc3 = Account()
print(acc1.num_acc)
print(Account.num_acc)
acc4 = Account()
print(Account.num_acc)

3
3
4


### Inheritance

In [12]:
class MinBalanceAccount(Account):
    def __init__(self, min_balance, num = '000-000-000000', amnt = 0, rate = 1.0):
        Account.__init__(self, num = num, amnt = amnt, rate = rate)
        
        self.minimum_balance = min_balance
        self.bonus_rate = 1.0

acc5 = MinBalanceAccount(10)
print(acc5.number)
print(acc5.balance)
print(acc5.rate)
print(acc5.minimum_balance)
print(acc5.bonus_rate)

acc5.deposit(1000)
print(acc5.balance)
acc5.obtain_interest()
print(acc5.balance)


000-000-000000
0
1.0
10
1.0
1000
1010.0


### method overriding

In [39]:
class MinBalanceAccount(Account):
    
    def __init__(self, min_balance, num = '000-000-000000', amnt = 0, rate = 1.0):
        Account.__init__(self, num = num, amnt = amnt, rate = rate)
        
        self.minimum_balance = min_balance
        self.bonus_rate = 1.0
        
    def withdraw(self, amnt): # 인출 기능 수정
    
        if self.balance - amnt < self.minimum_balance:
            print('Sorry, minimum balance must be maintained')
        else:
            Account.withdraw(self, amnt)
        
    def obtain_interest(self): #보너스 이율 반영
        self.balance += (self.balance)*((self.rate+self.bonus_rate)/100.0)

    def transfer(self, another, amnt):
        self.balance -= amnt
        another.balance += amnt

In [26]:

acc3=acc1+acc2
print(acc3.get_balance())

0


### practice _ trnasfer

In [124]:
class Account:
    num_acc = 0 
    def __init__ (self, num='000-000-000000', amnt=0, rate=1.0):
        self.number = num
        self.balance = amnt
        self.rate = rate
        Account.num_acc += 1
    def get_balance(self):
        return self.balance
    def set_balance(self, amnt):
        self.balance = amnt
    def deposit(self, money):
        self.balance += money
    def withdraw(self, money):
        self.balance -= money
    def obtain_interest(self):
        self.balance += self.balance * (self.rate/100)
    def __add__(self, another): #두 계좌 통합 기능
        new_acc = Account(amnt=self.balance+another.balance,rate=self.rate)
        return new_acc
    def transfer(self, another, amnt):
        if self.withdraw(amnt):another.deposit(amnt)
    def __repr__(self): #객체를 프린트 하면 알아서 지정값을 프린트하게 해주는 거 아리피알
        return str(self.balance)

In [125]:
class MinBalanceAccount(Account):
    
    def __init__(self, min_balance, num = '000-000-000000', amnt = 0, rate = 1.0):
        Account.__init__(self, num = num, amnt = amnt, rate = rate)
        
        self.minimum_balance = min_balance
        self.bonus_rate = 1.0
        
    def withdraw(self, amnt): # 인출 기능 수정
    
        if self.balance - amnt < self.minimum_balance:
            print('Sorry, minimum balance must be maintained')
        else:
            Account.withdraw(self, amnt)
            print("Your withdraw has successfully done")
            return True
        
    def obtain_interest(self): #보너스 이율 반영
        self.balance += (self.balance)*((self.rate+self.bonus_rate)/100.0)


In [126]:
acc1 = MinBalanceAccount(min_balance=0)
acc1.set_balance(500)
acc2 = MinBalanceAccount(min_balance=0)
acc2.set_balance(1000)

acc1.transfer(acc2, 700)
print(acc1.get_balance())
print(acc2.get_balance())
print(acc1, acc2)

Sorry, minimum balance must be maintained
500
1000
500 1000


### NumpY

In [134]:
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
# [1 2 3
#  4 5 6]
# 2x3 matrix

print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [137]:
a = np.zeros((2,2)) # 모든 값이 0인 2x2 array 생성
print(a)

b = np.ones((1,2)) # 모든 값이 1인 1x2 array 생성
print(b)

c = np.full((2,2), 7) # 모든 값이 7인 2x2 array 생성
print(c)

d = np.eye(2) # 2x2 단위행렬(Identity matrix) 생성
print(d)

e = np.random.random((2,2)) # 0~1 랜덤 값을 가지는 2x2 array 생성
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.9966646  0.17506621]
 [0.9911008  0.98462418]]


In [147]:
# 2차원 배열(3x4) 생성
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a, "\n")
print(sum(a), "\n")

# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
row_r1 = a[1, :] # 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape, "\n")

# 두 번째 열의 값들을 모두 가져오는 두 가지 방법
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape, "\n")
print(col_r2,col_r2.shape, "\n")


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[15 18 21 24] 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4) 

[ 2  6 10] (3,) 

[[ 2]
 [ 6]
 [10]] (3, 1) 



In [152]:
# 2차원 배열(3x2) 생성
# [[ 1 2]
# [ 3 4]
# [ 5 6]]

a = np.array([[1, 2], [3, 4], [5, 6]])
# [1 4 5] 1차원 행렬(3,)을 얻는 두 가지 방법

print(a[[0, 1, 2], [0, 1, 0]])
print()
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
print()
# [2 2] 1차원 행렬(2,)을 얻는 두 가지 방법
print(a[[0, 0], [1, 1]])
print()
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]

[1 4 5]

[2 2]

[2 2]


In [153]:
# 2차원 배열(4x3) 생성
# [[ 1 2 3]
# [ 4 5 6]
# [ 7 8 9]
# [ 10 11 12]]
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) # [1 6 7 11]
a[np.arange(4), b] += 10
print(a) 

# array([[11, 2, 3],
# [ 4, 5, 16],
# [17, 8, 9],
# [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [154]:
x = np.array([1, 2])
print(x.dtype) # prints “int64”
x = np.array([1.0, 2.0])
print(x.dtype) # “float64”
x = np.array([1, 2], dtype=np.int64) # 데이터타입 명시
print(x.dtype) # “int64”

int64
float64
int64


In [160]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum
print(x+y)
print(np.add(x,y))

# Elementwie difference
print(x-y)
print(np.subtract(x,y))

#Elementwise Product
print(x*y)
print(np.multiply(x,y))

#Elementwise division
print(x/y)
print(np.divide(x,y))

#Elementwise SQRT
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


### Dot product

In [164]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(w,v))

print(x.dot(v))
print(np.dot(x,v))

print(x.dot(y))
print(np.dot(x,y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### sum

In [170]:
x = np.array([[1, 2], [3, 4],[5,6],[7,8]])
print(np.sum(x))
# 모든 원소의 합
print(np.sum(x, axis=0)) # 각 열의 합
print(np.sum(x, axis=1)) # 각 행의 합


36
[16 20]
[ 3  7 11 15]


### transpose

In [171]:

x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)
# 전치행렬 (Transposed mat.)
v = np.array([1,2,3])
print(v)
# prints “[1 2 3]”
print(v.T)
# prints “[1 2 3]”

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### broadcasting

In [172]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복함 # 덩치를 부풀려서 계산 
print(vv)
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [173]:
v = np.array([1,0,1])
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복함

In [174]:
print(vv) 

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [175]:
print(x + vv)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [176]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
# 브로드캐스팅을 사용하여 x의 각 행에 v값을 더함 #tile이 없어도 바로 계산 가능하다
y = x + v
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [177]:
print(x.shape)

(4, 3)


In [185]:
v_rshp=v.reshape(1,-1)
print(v_rshp.shape)
print(v)
print(v_rshp)
print(x+v_rshp)

(1, 3)
[1 0 1]
[[1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


broadcasting 조건? axis 가 2개일 때
어느쪽이 1이 되거나 (axis 가) 또는
둘이 동일하거나

### practice _  연립 2차 방정식 풀기

In [190]:
matrix = np.array([[1, 1],[2, 1]])
x = np.linalg.inv(matrix)
y = [15, 25]

print(x.dot(y))

[10.  5.]


### pickle

In [197]:
import pickle

In [198]:
favorite_color = {"JUICE": "Green", "CoffeeAddict": "Blue"}

In [199]:
pickle.dump(favorite_color, open("save.p", "wb"))

In [200]:
favorite_color = pickle.load(open("save.p", "rb"))

In [202]:
print(favorite_color)

{'JUICE': 'Green', 'CoffeeAddict': 'Blue'}


### 과제1 - set.py

In [17]:
class mySet:
    def __init__ (self, member=[]):
        self.member = member
        
    def append(self, a):
        self.append(a)
    def delete(self, a):
        self.delete(a)
    def union(self, s2): #합집합
        return self.member + s2.member 
    def intersection (self, s2): #교집합
        self.intersection(s2)
    def difference(self, s2): #차집합
#        self.difference(s2)
        return self.member - s2.member
    def __add__(self, s2):
        self.union(s2)

In [18]:
a = mySet([1,2,3])
b = mySet([2,3,4])

c = a.union(b)
print(c)

d = a.difference(b)


[1, 2, 3, 2, 3, 4]


TypeError: unsupported operand type(s) for -: 'list' and 'list'